### ISSUE TITLE
Domains need to have A record, CNAME does not work

### ISSUE THREAD

**Issue by evilr00t** [GoogleCloudPlatform/gke-managed-certs#31]
Hello!

I don't know if this is a known issue altho I've faced it using gke-managed-certs.
If domain used for cert is a CNAME record then it does not work - even though it resolves to LB IP address.

```
Status:
  Certificate Name:    XXXX
  Certificate Status:  Provisioning
  Domain Status:
    Domain:  api.k8s.ansible.london
    Status:  FailedNotVisible
Events:      <none>
```

LetsEncrypt as far I know allows to use CNAME - so I would assume this is a managed-certs issue.

**Comment by krzykwas** [comment]
I've verified myself that GKE Managed Certificates indeed work with CNAMEs. The CNAME must point at a Google external LB IP address.

```yaml
apiVersion: networking.gke.io/v1beta1
kind: ManagedCertificate
metadata:
  name: test-certificate
spec:
  domains:
  - a.example.com
```

a.example.com.   IN      CNAME   b.example.com.
b.example.com.  IN      A       <<Google external LB IP address>>
