### ISSUE TITLE
Provide own private key and target for saving a cert

### ISSUE THREAD

**Issue by golonzovsky** [GoogleCloudPlatform/gke-managed-certs#32]
Not sure if this project is limited to GKE LB, or it may evolve into more generic use.

Would be useful to provide own private key from kubernetes secret and specify target for cert.

`sslCertificates` API resource does support providing a private key and exposes generated certs: https://cloud.google.com/compute/docs/reference/rest/v1/sslCertificates

Use case is to be able to use managed certificate without LB. E.g. provisioning public certs for kafka cluster. 

Something along the lines:
```
spec:
  domains:
    - example.com
  providedKeySecret:
    - secret-with-key
  targetCertSecret:
    - secret-example-com-crt
```
Maybe its not intention of this project and I need to look somewhere into `jetstack/cert-manager` GKE `sslCertificates` based issuer..
