### ISSUE TITLE
FailedNotVisible for domains w/ DNS managed by CloudFlare (proxy)

### ISSUE THREAD

**Issue by kpurdon** [GoogleCloudPlatform/gke-managed-certs#44]
Some details:

- I have a domain `synd.io`. 
- This domains DNS is managed by CloudFlare.
- An A record for `ce-staging` points to my external static IP `34.98.108.89` but dig resolves to the CloudFlare proxy IPs

```
kpurdon@syndio: ~ dig ce-staging.synd.io.

; <<>> DiG 9.10.6 <<>> ce-staging.synd.io.
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 3902
;; flags: qr rd ra; QUERY: 1, ANSWER: 2, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 512
;; QUESTION SECTION:
;ce-staging.synd.io.		IN	A

;; ANSWER SECTION:
ce-staging.synd.io.	215	IN	A	104.25.113.9
ce-staging.synd.io.	215	IN	A	104.25.112.9

;; Query time: 25 msec
;; SERVER: 192.168.86.1#53(192.168.86.1)
;; WHEN: Mon Mar 16 18:43:01 MDT 2020
;; MSG SIZE  rcvd: 79
```

- I created a managed certificate

```
apiVersion: networking.gke.io/v1beta1
kind: ManagedCertificate
metadata:
  name: ceweb-staging
spec:
  domains:
    - ce-staging.synd.io
```

- I created an ingress

```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ceweb
  annotations:
    kubernetes.io/ingress.allow-http: "false"
    kubernetes.io/ingress.global-static-ip-name: ceweb
    networking.gke.io/managed-certificates: ceweb-staging
spec:
  backend:
    serviceName: ceweb
    servicePort: 80
```

Everything works, except the domain status always results in FailedNotVisible. Is this an undocumented limitation, a misunderstanding by me, or a misconfiguration by me? 

Please let me know if I can provide any more details.
