### ISSUE TITLE
the server could not find the requested resource (get managedcertificates.networking.gke.io aa-example-certificate)

### ISSUE THREAD

**Issue by collbrain** [GoogleCloudPlatform/gke-managed-certs#46]
I am trying to automate our kubernetes deployments and trying to validate if things works. In that respect, create a managed certificate on gke using following yaml. The creation of cert is fine and it is active.

```
apiVersion: networking.gke.io/v1beta1
kind: ManagedCertificate
metadata:
  name: aa-example-certificate
spec:
  domains:
    - aa.xxx.io
```

Now, i am trying to access this using following code.

imported "github.com/GoogleCloudPlatform/gke-managed-certs/e2e/client"

Add following piece of code

            var clients *client.Clients
            clients, err := client.New("default")
            if err != nil {
                return err
            }
            mcrt, err := clients.ManagedCertificate.Get("aa-example-certificate")
            if err != nil {
                return err
            }
            fmt.Println(mcrt)

Getting following error
the server could not find the requested resource (get managedcertificates.networking.gke.io aa-example-certificate)

How to get cert info ?
