### ISSUE TITLE
I want to check out this alpha feature in GKE!

### ISSUE THREAD

**Issue by krzykwas** [GoogleCloudPlatform/gke-managed-certs#9]
Please reach out to manjotpahwa@google.com to learn more about alpha Managed Certificates in GKE.

**Comment by berstend** [comment]
Hey @krzykwas - just came across this project and was wondering if it can be used already?

Haven't tried it yet as I noticed the comments in another issue indicating it's not fully implemented yet.

Would be great to mention this in the readme, if that's the case. :-)

**Comment by markfermor** [comment]
I'm in the same boat. This looks really promising!

**Comment by brettcurtis** [comment]
I was able to get this working today - it's exactly what I'm after, looking good !

**Comment by michaelheyvaert** [comment]
Hi @krzykwas  @brettcurtis do you still need to reach out to manjotpahwa to try this out?

**Comment by brettcurtis** [comment]
I did not.

**Comment by bery** [comment]
Would you be willing to share the steps that you have taken? So we, who are keen to try the certs out, do not have to investigate :)

**Comment by brettcurtis** [comment]
I'll try to write something up today.

**Comment by brettcurtis** [comment]
I didn't have time to write anything up but was able to take make this public:
https://github.com/lzysh/ops-tf-module-k8s

If you follow the README.md at the end of the day you'll have a cluster running where you will only need to add this:

```yaml
---
apiVersion: networking.gke.io/v1beta1
kind: ManagedCertificate
metadata:
  name: nginx-example-tls
  namespace: nginx-example
spec:
  domains:
    - host.domain.com
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: nginx-example
  namespace: nginx-example
  annotations:
    kubernetes.io/ingress.allow-http: "false"
    networking.gke.io/managed-certificates: "nginx-example-tls"
spec:
  rules:
    - host: host.domain.com
      http:
        paths:
          - path: /*
            backend:
              serviceName: nginx-example-http
              servicePort: 80
```
...to get both dns and ssl on your ingress resources. I can try to help more when i have time if this is interesting to anyone.

**Comment by davidebelloni** [comment]
Hi,
I've followed the README and at the moment I've an Ingress with this alert (web console):

> This load balancer has no frontend configured


The ingress is:

```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: orchestrator-engine-dashboard-ingress
  labels:
    app: orchestrator-engine-dashboard
  annotations:
    kubernetes.io/ingress.allow-http: "false"
    kubernetes.io/ingress.global-static-ip-name: "orchestrator-test-addr"
    networking.gke.io/managed-certificates: "orchestrator-test"
spec:
  backend:
    serviceName: frontend-service
    servicePort: 80
  rules:
    - http:
        paths:
          - path: /*
            backend:
              serviceName: frontend-service
              servicePort: 80
          - path: /rest/*
            backend:
              serviceName: backend-service
              servicePort: 80
```

Cluster version: 1.11.7-gke.6
Node Pool scopes:
          - https://www.googleapis.com/auth/devstorage.read_only
          - https://www.googleapis.com/auth/logging.write
          - https://www.googleapis.com/auth/monitoring
          - https://www.googleapis.com/auth/servicecontrol
          - https://www.googleapis.com/auth/service.management.readonly
          - https://www.googleapis.com/auth/trace.append
          - https://www.googleapis.com/auth/cloud_debugger
NetPolicy enabled with permission to call HTTPS APIs and DNS
PSP enabled with this policy:
```
apiVersion: policy/v1beta1
kind: PodSecurityPolicy
metadata:
  name: restricted-psp
  annotations:
    seccomp.security.alpha.kubernetes.io/allowedProfileNames: 'docker/default'
    apparmor.security.beta.kubernetes.io/allowedProfileNames: 'runtime/default'
    seccomp.security.alpha.kubernetes.io/defaultProfileName:  'docker/default'
    apparmor.security.beta.kubernetes.io/defaultProfileName:  'runtime/default'
spec:
  privileged: false
  allowPrivilegeEscalation: false
  volumes:
    - 'configMap'
    - 'emptyDir'
    - 'projected'
    - 'secret'
    - 'downwardAPI'
    - 'hostPath'
    - 'persistentVolumeClaim'
  hostNetwork: false
  hostIPC: false
  hostPID: false
  runAsUser:
    rule: 'RunAsAny'
  seLinux:
    rule: 'RunAsAny'
  supplementalGroups:
    rule: 'MustRunAs'
    ranges:
      - min: 1
        max: 65535
  fsGroup:
    rule: 'MustRunAs'
    ranges:
      - min: 1
        max: 65535
  allowedHostPaths:
    - pathPrefix: "/etc/ssl/certs"
    - pathPrefix: "/usr/share/ca-certificates"
    - pathPrefix: "/var/log/managed_certificate_controller.log"
  readOnlyRootFilesystem: true
```

I'm missing something?
